### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by WJ714** [bgctw/Bigleaf.jl#25]
Hey Thomas,

It is absolutely an excellent bigleaf package using Julia. I tried to play with it this morning and but I got stacked in the very start step. I ca not install bigleaf.jl on Vscode by using Pkg.add(Bigleaf) or Pkg.add(url="https://github.com/bgctw/Bigleaf.jl"). Sorry I am also a newbie of Julia.
Could you please give me some hints to install that then I can continue to play with it?

Thank you very much!

Cheers,
Weijie

**Comment by bgctw** [comment]
What exactly are the problems with "cannot install"?
I just successfully tried 
```
using Pkg
Pkg.add("Bigleaf")
using Bigleaf
```
which makes Bigleaf available from the general registry.

**Comment by WJ714** [comment]
Thanks Thomas, I think it should work using the _Pkg.add("Bigleaf")_.
I just copy the error here, you might know what the mistake I made:
`
julia> Pkg.add("Bigleaf")
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Bigleaf [e2ae9153]:
 Bigleaf [e2ae9153] log:
 ├─possible versions are: 0.1.0-0.3.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.3.0
 ├─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: 0.1.0-0.2.0 or uninstalled, leaving only versions: 0.1.0-0.2.0
 │ └─StatsBase [2913bbd2] log:
 │   ├─possible versions are: 0.24.0-0.33.14 or uninstalled
 │   └─restricted to versions 0.32 by ESDL [359177bc], leaving only versions 0.32.0-0.32.2
 │     └─ESDL [359177bc] log:
 │       ├─possible versions are: 0.8.4 or uninstalled
 │       ├─restricted to versions * by ESDLPaperCode [2502ad13], leaving only versions 0.8.4
 │       │ └─ESDLPaperCode [2502ad13] log:
 │       │   ├─possible versions are: 0.0.0 or uninstalled
 │       │   └─ESDLPaperCode [2502ad13] is fixed to version 0.0.0
 │       └─ESDL [359177bc] is fixed to version 0.8.4
 └─restricted by compatibility requirements with DataFrames [a93c6f00] to versions: uninstalled — no versions left
   └─DataFrames [a93c6f00] log:
     ├─possible versions are: 0.11.7-1.3.2 or uninstalled
     └─restricted to versions 0.19-0.20 by ESDL [359177bc], leaving only versions 0.19.0-0.20.2
       └─ESDL [359177bc] log: see above
Stacktrace:
  [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
    @ Pkg.Resolve /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1063
  [2] propagate_constraints! (repeats 2 times)
    @ /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1000 [inlined]
  [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
    @ Pkg.Resolve /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1519
  [4] simplify_graph! (repeats 2 times)
    @ /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Resolve/graphtype.jl:1519 [inlined]
  [5] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:335
  [6] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1154
  [7] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::VersionNumber)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1139
  [8] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::VersionNumber)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1160
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations /opt/julia/share/julia/stdlib/v1.7/Pkg/src/Operations.jl:1176
 [10] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:268
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:149
 [12] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:144
 [13] #add#27
    @ /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:142 [inlined]
 [14] add
    @ /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:142 [inlined]
 [15] #add#26
    @ /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:141 [inlined]
 [16] add(pkg::String)
    @ Pkg.API /opt/julia/share/julia/stdlib/v1.7/Pkg/src/API.jl:141
 [17] top-level scope
    @ REPL[2]:1
`

**Comment by bgctw** [comment]
I am not familiar with resolving package dependencies. There might be conflicts with packages you already installed.

Can you , please, try with an empty [temporary project](https://pkgdocs.julialang.org/v1/api/#Pkg.activate):

- Pkg.activate(; temp=true)
- try adding Bigleaf again

If this works, you need to find the other package in you project (might be the global one) that causes the conflict with Bigleaf.jl.  
Do you need both packages in the current releases together?

@meggart - Since ESDL appears in the above conflict: Can you make sense of the dependency conflict  above? 
What is the recommended way of resolving?
Should I test the Bigleaf.jl explicitly with (older) 0.32 of StatsBase and release a new Bigleaf.jl? Or could you (@meggart ) release a version of ESDL with compat entry for StatsBase  of 0.33, as already in your development version?

**Comment by WJ714** [comment]
Thanks Thomas, it works with an empty temporary project. :+1: 
> Do you need both packages in the current releases together?

Not really for now. 
But would be interesting if I can use both packages in the near future. :+1:

**Comment by bgctw** [comment]
I tried testing Bigleaf with StatsBase 0.32. However, I failed because Missing.jl v1 also requires StatsBase 0.33. Hence I cannot downgrade the dependency without a chain of subsequent events.
Until ESDL releases a  version that works with StatsBase 0.33 you should be able to use both packages together by using ESDL development version by saying
`Pkg.develop(url="https://github.com/esa-esdl/ESDL.jl.git")`
and if they release a new version by switching back to the Registry version by saying
`Pkg.free("ESDL")`

**Comment by meggart** [comment]
Hi Thomas and Weijie, 

ESDL.jl does support StatsBase v0.33 https://github.com/esa-esdl/ESDL.jl/blob/85c6f9ad6bcf74cee5dba42fd1a7c36f00da0efa/Project.toml#L36, so I don't really understand why the error occurs. Have you tried updating ESDL?

**Comment by bgctw** [comment]
Dear Weijie
since, this seems to be an issue of updating your local packages, I close this issue for Bigleaf.jl.
