### ISSUE TITLE
change package name to BigLeaf.jl

### ISSUE THREAD

**Issue by lazarusA** [bgctw/Bigleaf.jl#30]
Nice package. 

What about changing the name to `BigLeaf.jl` to be closer to the [naming conventions](https://pkgdocs.julialang.org/v1/creating-packages/#Package-naming-guidelines). 

Now that I noticed this package I realised that I coded some of the functions here, so doing some PRs here will be best, instead of creating a new package.

**Comment by bgctw** [comment]
After a discussion on Slack, initiated during Registration of the renamed package, I learned that renaming the case of a package creates more problem than it solvers. An example is having two packages with the same name on lower-case file systems in the local registry. 

Hence, we need to stick to the lowercase package name.
